### ISSUE TITLE
How do i use YOLO 3D with ZED camera ROS2 wrapper?

### ISSUE THREAD

**Issue by AdimasBarelang** [Ar-Ray-code/darknet_ros_fp16#12]
I want to use YOLO 3D so that i can grab the depth or distance that captured by ZED camera. Can you give me a guidance that will launch the YOLO 3D bounding box in ur repo?

**Comment by Ar-Ray-code** [comment]
First of all, I am neither a member of stereolabs nor your free consultant.

When obtaining 3D coordinates, you can use the 2D-coordinates of the RGB image to calculate the coordinates of the depth image using the median of the five neighbourhoods. If these are real world coordinates, they will be corrected for camera angle and distortion according to the official reference. darknet_ros_fp16 does not require any processing and you will need to create an external node.

**Comment by AdimasBarelang** [comment]
> I want to use YOLO 3D so that i can grab the depth or distance that captured by ZED camera. Can you give me a guidance that will launch the YOLO 3D bounding box in ur repo?

(I am sorry if i sounds so rude to you, I don't mean it. But thanks for ur answer and advice to me😊)
