### ISSUE TITLE
Installation without CUDA?

### ISSUE THREAD

**Issue by MOVAX19** [Ar-Ray-code/darknet_ros_fp16#4]
Hi!
I'm trying to implement darknet_ros for ROS2 but my laptop doesn't have an dedicated graphic card and it seems that the foxy branch of darknet_ros doesn't compile, so I was wondering if is it possible to build your implementation without CUDA?

**Comment by Ar-Ray-code** [comment]
??
If the NVIDIA graphics card is not detected, the program will automatically compile for the CPU.
Have you tried it❓
If it fails, please send me the error log.

**Comment by MOVAX19** [comment]
I followed the steps stated in the documentation, however I got the following error after trying to build the package:

```Starting >>> darknet_ros
--- stderr: darknet_ros
CMake Error: The source "/home/movax/drone_ws/src/darknet_ros_yolov4/darknet_ros/darknet_ros/CMakeLists.txt" does not match the source "/home/movax/drone_ws/src/darknet_ros/darknet_ros/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
---
Failed   <<< darknet_ros [0.08s, exited with code 1]

Summary: 0 packages finished [0.30s]
  1 package failed: darknet_ros
  1 package had stderr output: darknet_ros```

**Comment by Ar-Ray-code** [comment]
About this msg,
> CMake Error: The source "/home/movax/drone_ws/src/darknet_ros_yolov4/darknet_ros/darknet_ros/CMakeLists.txt" does not match the source "/home/movax/drone_ws/src/darknet_ros/darknet_ros/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
> 
> ---

Please try to delete "drone_ws/build/" and "drone_ws/install/" to delete cache.
